[workspace]
resolver = "3"
members = ["overlad-api", "overlad-backend", "overlad-frontend"]

[workspace.dependencies]
chrono = "0.4.42"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
