[workspace]
resolver = "3"
members = ["overlad-api", "overlad-backend", "overlad-frontend", "overlad-lib"]

[workspace.dependencies]
ab_glyph = "0.2.31"
chrono = "0.4.42"
image = "0.25.6"
imageproc = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
