[package]
name = "overlad-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = { workspace = true }
chrono = { workspace = true }
current-previous = "0.1.3"
image = { workspace = true }
imageproc = { workspace = true }
serde = { workspace = true }
